[package]
name = "nube"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.6"
rand_core = { version = "*", features = ["getrandom"] }
ff = "*"
sha3 = "*"
